name: Test

on: [push]

jobs:
  test:
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    runs-on:  ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: test
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
    - name: Install cppimport
      run: |
        pip install --no-use-pep517 --no-deps --disable-pip-version-check -e .
    - name: Lint with flake8
      run: |
        flake8 . 
    - name: Check formatting with black
      run: |
        black --check . 
    - name: Check import ordering with isort
      run: |
        isort --check . 
    - name: Test
      run: |
        py.test
